import type { Producto } from '@/types/producto'

export const PRODUCTOS_MOCK: Producto[] = [
  {
    id: '1',
    nombre: 'Borojó Fresco del Baudó',
    descripcion: 'Fruta amazónica rica en aminoácidos, vitaminas y minerales. Cosechada a mano en el río Baudó.',
    historia: 'El borojó ha sido alimento sagrado del pueblo Embera por siglos. Su pulpa densa es base de bebidas energéticas y medicinas tradicionales.',
    precio: 18000,
    unidad: 'kg',
    stock: 50,
    diasAlistamientoMin: 2,
    diasAlistamientoMax: 4,
    alcance: 'NACIONAL',
    activo: true,
    comercio: {
      nombre: 'Finca Agroforestal Baudó Verde',
      municipio: 'Quibdó, Chocó',
      verificado: true,
      totalVentas: 47,
      calificacion: 4.8,
      totalReviews: 31,
    },
  },
  {
    id: '2',
    nombre: 'Plátano Hartón Orgánico',
    descripcion: 'Plátano de la variedad hartón, cultivado sin agroquímicos en las riberas del río Atrato.',
    precio: 4500,
    unidad: 'racimo',
    stock: 120,
    diasAlistamientoMin: 1,
    diasAlistamientoMax: 3,
    alcance: 'LOCAL',
    activo: true,
    comercio: {
      nombre: 'Asociación Campesina Atrateña',
      municipio: 'Istmina, Chocó',
      verificado: true,
      totalVentas: 23,
      calificacion: 4.5,
      totalReviews: 18,
    },
  },
  {
    id: '3',
    nombre: 'Cacao Fino de Aroma Nativo',
    descripcion: 'Granos de cacao nativo fino de aroma, fermentados y secados artesanalmente. Certificado de origen chocoano.',
    precio: 32000,
    unidad: 'kg',
    stock: 30,
    diasAlistamientoMin: 3,
    diasAlistamientoMax: 7,
    alcance: 'NACIONAL',
    activo: true,
    comercio: {
      nombre: 'Cooperativa Cacao Chocó',
      municipio: 'Tadó, Chocó',
      verificado: true,
      totalVentas: 61,
      calificacion: 4.9,
      totalReviews: 44,
    },
  },
  {
    id: '4',
    nombre: 'Aceite de Chocolatillo',
    descripcion: 'Aceite vegetal extraído de la palma de chocolatillo, usado en gastronomía tradicional afrochocoana.',
    precio: 25000,
    unidad: 'litro',
    stock: 20,
    diasAlistamientoMin: 4,
    diasAlistamientoMax: 8,
    alcance: 'NACIONAL',
    activo: true,
    comercio: {
      nombre: 'Mujeres Emprendedoras del San Juan',
      municipio: 'Condoto, Chocó',
      verificado: true,
      totalVentas: 0,
      calificacion: 4.7,
      totalReviews: 5,
    },
  },
  {
    id: '5',
    nombre: 'Panela Negra Artesanal',
    descripcion: 'Panela elaborada en trapiche de madera, sin aditivos. Endulzante ancestral de la cocina chocoana.',
    precio: 8000,
    unidad: 'bloque 500g',
    stock: 80,
    diasAlistamientoMin: 2,
    diasAlistamientoMax: 5,
    alcance: 'AMBOS',
    activo: true,
    comercio: {
      nombre: 'Trapiche Familiar Los Murillo',
      municipio: 'Bagadó, Chocó',
      verificado: true,
      totalVentas: 15,
      calificacion: 4.6,
      totalReviews: 12,
    },
  },
  {
    id: '6',
    nombre: 'Piña Perolera del Pacífico',
    descripcion: 'Piña pequeña y dulce, variedad local del Pacífico colombiano. Altamente aromática, ideal para jugos y coctelería.',
    precio: 6000,
    unidad: 'unidad',
    stock: 60,
    diasAlistamientoMin: 1,
    diasAlistamientoMax: 2,
    alcance: 'LOCAL',
    activo: true,
    comercio: {
      nombre: 'Productores Unidos Alto Baudó',
      municipio: 'Pie de Pató, Chocó',
      verificado: true,
      totalVentas: 38,
      calificacion: 4.4,
      totalReviews: 22,
    },
  },
]
