'use client'

import { useEffect, useEffectEvent, useState } from 'react'
import Link from 'next/link'
import { apiFetch } from '@/lib/api/client'
import { formatearPrecio } from '@/lib/formatearPrecio'

type Producto = { id: number; nombre: string; unidad: string; stock: number; stockReservado: number; disponible: number; costoPromedio: number; valorInventario: number }
type Movimiento = { id: number; tipo: string; cantidad: number; stockAnterior: number; stockPosterior: number; costoUnitario: number; createdAt: string; producto: { nombre: string } }
type Kardex = { existencias: Producto[]; movimientos: Movimiento[] }

export default function KardexPage() {
  const [data, setData] = useState<Kardex | null>(null); const [productoId, setProductoId] = useState(''); const [desde, setDesde] = useState(''); const [hasta, setHasta] = useState(''); const [error, setError] = useState<string | null>(null)
  async function cargar() { try { const q = new URLSearchParams(); if (productoId) q.set('productoId', productoId); if (desde) q.set('desde', desde); if (hasta) q.set('hasta', hasta); const r = await apiFetch<{ data: Kardex }>(`/inventario/kardex?${q}`); setData(r.data) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo cargar el Kardex.') } }
  const cargarInicial = useEffectEvent(cargar)
  useEffect(() => { void cargarInicial() }, [])
  return <div className="mx-auto max-w-6xl space-y-6 pb-10"><div><Link href="/comerciante/inventario" className="text-xs text-[#1A1A1A]/45">← Inventario</Link><h1 className="mt-1 text-3xl text-[#1A1A1A]" style={{ fontFamily: 'var(--font-dm-serif), Georgia, serif' }}>Kardex valorizado</h1><p className="mt-1 text-sm text-[#1A1A1A]/55">Trazabilidad de existencias, costos y valor del inventario.</p></div><div className="flex flex-wrap gap-2 rounded-2xl border bg-white p-4"><select value={productoId} onChange={e => setProductoId(e.target.value)} className="rounded-xl border p-2 text-sm"><option value="">Todos los productos</option>{data?.existencias.map(p => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select><input type="date" value={desde} onChange={e => setDesde(e.target.value)} className="rounded-xl border p-2 text-sm"/><input type="date" value={hasta} onChange={e => setHasta(e.target.value)} className="rounded-xl border p-2 text-sm"/><button onClick={() => void cargar()} className="rounded-xl bg-[#2D6A4F] px-4 py-2 text-sm font-semibold text-white">Filtrar</button></div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[750px] w-full text-sm"><thead className="bg-[#F8F5F0] text-left"><tr><th className="p-3">Producto</th><th>Disponible</th><th>Costo promedio</th><th>Valor inventario</th></tr></thead><tbody>{data?.existencias.map(p => <tr key={p.id} className="border-t"><td className="p-3 font-medium">{p.nombre}</td><td>{p.disponible} {p.unidad}</td><td>{formatearPrecio(p.costoPromedio)}</td><td className="font-semibold">{formatearPrecio(p.valorInventario)}</td></tr>)}</tbody></table></section><section className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[800px] w-full text-sm"><thead className="bg-[#F8F5F0] text-left"><tr><th className="p-3">Fecha</th><th>Producto</th><th>Movimiento</th><th>Cantidad</th><th>Saldo</th><th>Costo</th></tr></thead><tbody>{data?.movimientos.map(m => <tr key={m.id} className="border-t"><td className="p-3">{new Date(m.createdAt).toLocaleString('es-CO')}</td><td>{m.producto.nombre}</td><td>{m.tipo}</td><td>{m.cantidad > 0 ? '+' : ''}{m.cantidad}</td><td>{m.stockAnterior} → {m.stockPosterior}</td><td>{formatearPrecio(Number(m.costoUnitario))}</td></tr>)}</tbody></table></section></div>
}
