'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/Button'
import { apiFetch } from '@/lib/api/client'
import { formatearPrecio } from '@/lib/formatearPrecio'

type Cuenta = { id: number; tipo: 'INGRESO' | 'EGRESO'; concepto: string; contraparte?: string | null; montoOriginal: number | string; montoPagado: number | string; estado: string; fechaVencimiento?: string | null }
type Caja = { ingresos: number; egresos: number; saldo: number }

export default function CuentasOperativasPage() {
  const [cuentas, setCuentas] = useState<Cuenta[]>([]); const [caja, setCaja] = useState<Caja | null>(null)
  const [tipo, setTipo] = useState<'INGRESO' | 'EGRESO'>('EGRESO'); const [concepto, setConcepto] = useState(''); const [monto, setMonto] = useState('')
  const [error, setError] = useState<string | null>(null); const [guardando, setGuardando] = useState(false)
  async function cargar() { try { const [a, b] = await Promise.all([apiFetch<{ cuentas: Cuenta[] }>('/inventario/cuentas'), apiFetch<{ data: Caja }>('/inventario/caja/resumen')]); setCuentas(a.cuentas ?? []); setCaja(b.data) } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo cargar la caja.') } }
  useEffect(() => { void cargar() }, [])
  async function crear(e: FormEvent) { e.preventDefault(); if (!concepto.trim() || Number(monto) <= 0) return setError('Escribe concepto y monto mayor que cero.'); setGuardando(true); try { await apiFetch('/inventario/cuentas', { method: 'POST', body: { tipo, concepto, montoOriginal: Number(monto) } }); setConcepto(''); setMonto(''); await cargar() } catch (x) { setError(x instanceof Error ? x.message : 'No se pudo crear la cuenta.') } finally { setGuardando(false) } }
  async function abonar(cuenta: Cuenta) { const valor = window.prompt(`Abono para ${cuenta.concepto} (COP)`); if (!valor || Number(valor) <= 0) return; try { await apiFetch(`/inventario/cuentas/${cuenta.id}/abonos`, { method: 'POST', body: { monto: Number(valor) } }); await cargar() } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo registrar el abono.') } }
  return <div className="mx-auto max-w-5xl space-y-6 pb-10"><div><Link href="/comerciante/contabilidad" className="text-xs text-[#1A1A1A]/45">← Contabilidad</Link><h1 className="mt-1 text-3xl text-[#1A1A1A]" style={{ fontFamily: 'var(--font-dm-serif), Georgia, serif' }}>Cuentas y caja</h1></div>{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 sm:grid-cols-3">{[['Ingresos', caja?.ingresos], ['Egresos', caja?.egresos], ['Saldo', caja?.saldo]].map(([t,v]) => <div key={t as string} className="rounded-2xl border bg-white p-4"><p className="text-xs uppercase text-[#1A1A1A]/45">{t}</p><b className="mt-2 block text-xl text-[#1B4332]">{formatearPrecio(Number(v ?? 0))}</b></div>)}</div><form onSubmit={crear} className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Nueva cuenta</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><select value={tipo} onChange={e => setTipo(e.target.value as 'INGRESO'|'EGRESO')} className="rounded-xl border p-2.5"><option value="INGRESO">Por cobrar</option><option value="EGRESO">Por pagar</option></select><input value={concepto} onChange={e => setConcepto(e.target.value)} placeholder="Concepto" className="rounded-xl border px-3 py-2.5"/><input type="number" min="1" value={monto} onChange={e => setMonto(e.target.value)} placeholder="Monto COP" className="rounded-xl border px-3 py-2.5"/></div><div className="mt-4 flex justify-end"><Button type="submit" loading={guardando}>Crear cuenta</Button></div></form><section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4"><h2 className="font-semibold">Pendientes y abonos</h2></div>{cuentas.length ? cuentas.map(c => { const saldo = Number(c.montoOriginal)-Number(c.montoPagado); return <div key={c.id} className="flex items-center justify-between gap-3 border-b p-4"><div><p className="font-medium">{c.concepto}</p><p className="text-xs text-[#1A1A1A]/45">{c.tipo === 'INGRESO' ? 'Por cobrar' : 'Por pagar'} · {c.estado}</p></div><div className="text-right"><p className="font-semibold">{formatearPrecio(saldo)}</p>{saldo > 0 && <button onClick={() => void abonar(c)} className="mt-1 text-xs font-semibold text-[#2D6A4F]">Registrar abono</button>}</div></div> }) : <p className="p-8 text-center text-sm text-[#1A1A1A]/45">No hay cuentas registradas.</p>}</section></div>
}
